/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx public/models/monkey_draco.glb 
*/

import React, { useContext, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshPhysicalMaterial } from 'three'
import { ConfiguratorContext } from '../ConfiguratorContext'

const model_url = "/models/monkey_draco.glb"

export function Monkey(props) {
  
  const { nodes, materials } = useGLTF(model_url)
  
  const {configProps, setConfigProps} = useContext(ConfiguratorContext)
  
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} >
        <meshStandardMaterial color={configProps} roughness={0.3} opacity={1}/>
      </mesh>
    </group>
  )
}


useGLTF.preload(model_url)
